# Generated by Django 5.2.3 on 2025-06-30 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasync",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_syncs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="datasync",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.externalservice",
            ),
        ),
        migrations.AddField(
            model_name="integrationhealth",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.externalservice",
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.externalservice",
            ),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_endpoints",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.externalservice",
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="tenants.tenant",
            ),
        ),
    ]
